N8N_WEBHOOK_URL = "https://ihisam722.app.n8n.cloud/webhook-test/a6820b65-76cf-402b-a934-0f836dee6ba0/chat"
IMAGES_GOOGLE_SHEET_URL = "https://docs.google.com/spreadsheets/d/189Rwsit3PMBCyQZeQevGhDxZbENh8I779wyhNMZF-T0/edit?usp=sharing"
VIDEOS_GOOGLE_SHEET_URL = "https://docs.google.com/spreadsheets/d/1ekqSLg1xRWDxHwfZQyiOGfjSYQfGoYoGCVaUQHnNOOs/edit?usp=sharing"
ELEVEN_LABS_API_KEY = "agent_01jvft97waft7rgnwh806ksk7q"
